[package]
name = "victorem"
version = "0.1.0"
authors = ["VictoremWinbringer <victor@mail.ru>"]
edition = "2018"

[dependencies]
bincode = "*"
serde_derive = "*"
serde = "*"
log = "*"
simplelog = "*"
threadpool = "*"
lazy_static = "*"