[package]
name = "victorem"
version = "0.1.0"
edition = "2018"
description = "UPD Game Server Framework"
license = "MIT"
authors = ["https://github.com/VictoremWinbringer"]
[dependencies]
bincode = "1.0.1"
serde_derive = "1.0.82"
serde = "1.0.82"
itertools = "0.8.0"